name: nfx-exchange-backend
services:
- name: backend
  source_dir: /
  github:
    repo: your-username/your-repo
    branch: main
  run_command: node dist/index.js
  build_command: pnpm install && pnpm build:backend
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 4000
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "4000"
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_USER
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
  - key: DB_NAME
    value: ${db.DATABASE}
  - key: DB_PORT
    value: ${db.PORT}

databases:
- name: db
  engine: MYSQL
  version: "8"